InternetForum/Models/Post.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InternetForum.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Theme { get; set; }
        public string Description { get; set; }
        public int LikeCount { get; set; }
        public int CommentCount { get; set; }
        public string UserId { get; set; }
        public User User { get; set; }
        public List<Comment> Comments { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}

InternetForum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternetForum;
using InternetForum.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using System.Reflection.Metadata.Ecma335;
using InternetForum.ViewModels;


namespace InternetForum.Controllers
{

  
    [Authorize]
    public class PostsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public PostsController(UserManager<User> userManager,ApplicationContext context, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Posts
        public async Task<IActionResult> Index(int? page)
        {
      
            User user = await _userManager.GetUserAsync(User);
            IEnumerable<Post> posts = _context.Posts.Include(p => p.Comments).Include(pp => pp.User);
            return View(posts);
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.Include("Comments")
                .FirstOrDefaultAsync(m => m.Id == id);
            post.Comments = _context.Comments.Include("User").Where(c => c.PostId == post.Id).ToList();
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Theme,Description")] Post post)
        {
            if (ModelState.IsValid)
            {

                post.CreatedOn = DateTime.UtcNow;
                post.LikeCount = 0;
                post.CommentCount = 0;
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                post.UserId = user.Id;
                _context.Add(post);
             
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
      
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
        
                return NotFound();
            }
        
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Theme,Description")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
       
                var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);

            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
        [HttpPost]

        public async Task<IActionResult> Comment(int postId,  string content, DateTime date, List<Like> like)

        {
           
            User user = await _userManager.GetUserAsync(User);
            ViewBag.CurrentUserId = user.Id;
            Post post = await _context.Posts.FirstOrDefaultAsync(m => m.Id == postId);

            Comment comment = new Comment() { PostId = postId, UserId = user.Id , Content = content, CommentDate= DateTime.UtcNow, Likes = like};
            user.AnswerCount = user.AnswerCount + 1;
            post.CommentCount = post.CommentCount + 1;
            _context.Add(comment);
            _context.Update(post);
            await _context.SaveChangesAsync();
            return Ok(Json("{\"count\":" + post.CommentCount +" }"));
        }
        public async Task<IActionResult> Like(int id)
        {
            
            User user = await _userManager.GetUserAsync(User);
            Like like = new Like() { CommentId = id, UserId = user.Id };
             _context.Add(like);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Unlike(int id)
        {
            var like = await _context.Likes.FindAsync(id);
            _context.Likes.Remove(like);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

InternetForum/Views/Posts/Create.cshtml
@model InternetForum.Models.Post

@{
    ViewData["Title"] = "Create";
}




<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Theme" class="control-label"></label>
                <input asp-for="Theme" class="form-control" />
                <span asp-validation-for="Theme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Пойти обратно...</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InternetForum/Views/Posts/Delete.cshtml
@model InternetForum.Models.Post

@{
    ViewData["Title"] = "Delete";
}



<h3>Уверены, что хотите удалить?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Theme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Theme)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LikeCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LikeCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CommentCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CommentCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Пойти обратно...</a>
    </form>
</div>

InternetForum/Views/Posts/Details.cshtml
@model InternetForum.Models.Post

@{
    ViewData["Title"] = "Details";
}



<h1>Тема:@Model.Theme</h1>
<div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
    <div class="lh-100">
        <h6 class="mb-0 text-black-50 lh-100">@Model.Description</h6>

        <strong class="text-black-50 ">
            Лайков - @Model.LikeCount ,
        </strong>
        <strong class="text-black-50 ">
            Ответов - @Model.CommentCount
        </strong>
        <small class="text-muted">
        @Model.CreatedOn
    </small>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
    <a asp-action="Index">Пойти обратно...</a>
</div>

InternetForum/Views/Posts/Edit.cshtml
@model InternetForum.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <div class="form-group">
            <label asp-for="Theme" class="control-label"></label>
            <input asp-for="Theme" class="form-control" />
            <span asp-validation-for="Theme" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
    </form>
</div>
</div>

<div>
    <a asp-action="Index">Пойти обратно...</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InternetForum/Views/Posts/Index.cshtml
@model IEnumerable<InternetForum.Models.Post>



<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Самые яростные дискуссии начинаются здесь.</h1>
        <p class="lead text-muted">
            У каждого свой горизонт знаний и интересов, а когда он сужается до точки, человек говорит: «Это моя точка зрения».<br />
            Давид Гильберт

        </p>
        <p>
            <a class="text-dark" asp-action="Create">Cоздай тему!</a>
        </p>
    </div>
</section>
@foreach (var item in Model.OrderByDescending(x => x.CreatedOn))
{

    <div class="col-md-10">
        <div class="card mb-4 shadow-sm">
            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Ещё...
                </button>
                <div class="dropdown-menu">
                    <p><a class="text-dark" asp-action="Edit" asp-route-id="@item.Id">Изменить </a></p>
                    <p><a class="text-dark" asp-action="Delete" asp-route-id="@item.Id">Удалить </a></p>
                    <p><a class="text-dark" asp-action="Details" asp-route-id="@item.Id">Детали </a></p>
                </div>
            </div>
            <p>Тема от: @item.User</p>
            <div class="card-header">
                @item.Theme
            </div>
            <div class="card-body">

                <p><a class="text-dark" asp-action="Details" asp-route-id="@item.Id">Посмотреть содержимое...</a></p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">

                        <a onclick="openCommentForm(@item.Id)" style="cursor: pointer" , class="btn btn-info btn-sm">Ответить(@item.CommentCount)</a>
                      

                    </div>

                    <small class="text-muted">@item.CreatedOn</small>
                </div>
                <div id="postdiv-@item.Id" style="display:none">

                    <textarea id="posttext-@item.Id"></textarea>

                    <input type="button" id="postComment" onclick="sendComment('@item.Id')" onClick="refreshPage()" value="Отправить" class="btn btn-info btn-success" />
                </div>
            </div>
            <div class="my-3 p-3 bg-white rounded box-shadow">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        Последние ответы
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu col-10" role="menu" aria-labelledby="dropdownMenu1">
                        @foreach (Comment comment in item.Comments.OrderByDescending(x => x.CommentDate))
                        {
                            <div class="media text-muted pt-lg-4">

                                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                                    <strong class="d-block text-gray-dark">@comment.User.UserName (@comment.User.AnswerCount ответов на Форуме) </strong>
                                    @comment.Content
                                   
                     
                                </p>
                                <small class="text-muted">@comment.CommentDate</small>
                            </div>
                        }
                    </ul>
                </div>
            </div>

        </div>
    </div>
}
<script>
    function openCommentForm(postId)
    {
$('#postdiv-' + postId).toggle();
    }
        function sendComment(postId) {
            $.ajax( {
                url: '@Url.Action("Comment", "Posts")',
                type: 'POST',
                data: { 'postId': postId, 'Content': $('#posttext-' + postId).val() },
                success: function (data, status, xhr) {
                    console.log("Все нормально.");
                    window.location.reload();
                    console.log(data);
                    console.log(status);
                    console.log(xhr);

                    var result = JSON.parse(data.value)
                    $('#comentcout-' + postId).html(result.count);
                    console.log(result)


                },
                error: function (jqXhr, textStatus, errorMessage) {
                    console.log("Что-то пошло не так..")
                    console.log(jqXhr);
                    console.log(textStatus);
                    console.log(errorMessage);
                }
            });
        }

</script>